var records = [
{"event":"executeBegin","executeID":1},
    {"event":"output","data":{"output":"starting"}},
{"event":"link","executeID":1,"linkID":5,"data":{"type":"TickObject"}},
{"event":"cause","executeID":1,"linkID":5,"causeID":1},
{"event":"link","executeID":1,"linkID":6,"data":{"type":"PROMISE"}},
{"event":"cause","executeID":1,"linkID":6,"causeID":1},
{"event":"link","executeID":1,"linkID":7,"data":{"type":"Timeout"}},
{"event":"cause","executeID":1,"linkID":7,"causeID":1},
{"event":"link","executeID":1,"linkID":8,"data":{"type":"TIMERWRAP"}},
{"event":"cause","executeID":1,"linkID":8,"causeID":1},
{"event":"link","executeID":1,"linkID":9,"data":{"type":"PROMISE"}},
{"event":"cause","executeID":1,"linkID":9,"causeID":6},
{"event":"executeEnd","executeID":1},
{"event":"executeBegin","executeID":5,"causeID":1},
{"event":"executeEnd","executeID":5},
{"event":"executeBegin","executeID":8,"causeID":1},
{"event":"executeBegin","executeID":7,"causeID":1},
{"event":"output","data":{"output":"resolving promise in timeout"}},

{"event":"link","executeID":7,"linkID":10,"data":{"type":"TickObject"}},
{"event":"cause","executeID":7,"linkID":10,"causeID":7},
{"event":"executeEnd","executeID":7},
{"event":"executeEnd","executeID":8},
{"event":"executeBegin","executeID":10,"causeID":7},
{"event":"executeEnd","executeID":10},
{"event":"executeBegin","executeID":9,"causeID":6},
{"event":"output","data":{"output":"in \"then\": true"}},

{"event":"link","executeID":9,"linkID":11,"data":{"type":"TickObject"}},
{"event":"cause","executeID":9,"linkID":11,"causeID":9},
{"event":"executeEnd","executeID":9},
{"event":"executeBegin","executeID":11,"causeID":9},
{"event":"executeEnd","executeID":11}
]